### ISSUE TITLE
Update Dependencys

### ISSUE THREAD

**Issue by SirNiggo** [billsonnn/habboapi-starter#1]
Hi,

could you please update the starters dependencys and publish the new core modules to NPM? Setup doesnt work otherwise.

Thanks!

**Comment by billsonnn** [comment]
Until I do so here’s what you can do (remember this is only development right now)

Download habboapi-core

If your familiar with typescript you can run TSC on each directory ( common, emulator, habbo, security)

Cd into the /out-tsc directory’s run npm link in each out-tsc for each package cd back to the main directory and run npm link @habboapi/common for example and run for each one

The main directory will then run (ignore habboapi-starter for now)

I know this is a mess, I hope it makes sense!
